apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume
  labels:
    app: pv-volume #app: #name type
spec:
   accessModes:
     - ReadWriteOnce # data can be read/written by a single node
   capacity: #amount of storage pv can allot from external volume/ebs 
      storage: 15Gi
   storageClassName: standard #matches with pvc and depends on the type of external volume
   volumeMode: Filesystem #since ebs is used we use in this volume mode
   persistentVolumeReclaimPolicy: Retain #data will be retained even after pv is deleted
   hostPath: /mnt/data/nginxvol #ensure accessModes , storageClassName and VolumeMode matches with pvc